#ifndef __USB10_H__
#define __USB10_H__

#include <stdint.h>
#include <string.h>

#define	USB10_STATUS_ERROR_S	30
#define	USB10_STATUS_ERROR_M	0x01
#define	USB10_STATUS_ERROR(X)	(((X) >> USB10_STATUS_ERROR_S) & USB10_STATUS_ERROR_M)
#define	USB10_STATUS_ERROR_BIT	(USB10_STATUS_ERROR_M << USB10_STATUS_ERROR_S)	

#define	USB10_STATUS_REPORT_S	29	
#define	USB10_STATUS_REPORT_M	0x01
#define	USB10_STATUS_REPORT(X)	(((X) >> USB10_STATUS_REPORT_S) & USB10_STATUS_REPORT_M)
#define	USB10_STATUS_REPORT_BIT	(USB10_STATUS_REPORT_M << USB10_STATUS_REPORT_S)	

#define	USB10_STATUS_BUSY_S	28	
#define	USB10_STATUS_BUSY_M	0x01
#define	USB10_STATUS_BUSY(X)	(((X) >> USB10_STATUS_BUSY_S) & USB10_STATUS_BUSY_M)
#define	USB10_STATUS_BUSY_BIT	(USB10_STATUS_BUSY_M << USB10_STATUS_BUSY_S)

#define	USB10_STATUS_RECEIVED_S		27
#define	USB10_STATUS_RECEIVED_M		0x01
#define	USB10_STATUS_RECEIVED(X)	(((X) >> USB10_STATUS_RECEIVED_S) & USB10_STATUS_RECEIVED_M)
#define	USB10_STATUS_RECEIVED_BIT	(USB10_STATUS_RECEIVED_M << USB10_STATUS_RECEIVED_S)

#define	USB10_STATUS_PID_S	16
#define	USB10_STATUS_PID_M	0xff
#define	USB10_STATUS_PID(X)	(((X) >> USB10_STATUS_PID_S) & USB10_STATUS_PID_M)

#define	USB10_STATUS_STATE_S	0	
#define	USB10_STATUS_STATE_M	0xff
#define	USB10_STATUS_STATE(X)	(((X) >> USB10_STATUS_PID_S) & USB10_STATUS_PID_M)

#define	USB10_CMD_START_S	31
#define	USB10_CMD_START_M	0x01
#define	USB10_CMD_START(X)	(((X) >> USB10_CMD_START_S) & USB10_CMD_START_M)
#define	USB10_CMD_START_BIT	(USB10_CMD_START_M << USB10_CMD_START_S)

#define	USB10_CMD_ADDR_S	24
#define	USB10_CMD_ADDR_M	0x7f
#define	USB10_CMD_ADDR(X)	(((X) >> USB10_CMD_ADDR_S) & USB10_CMD_ADDR_M)
#define	USB10_CMD_SET_ADDR(X)	(((X) & USB10_CMD_ADDR_M) << USB10_CMD_ADDR_S)

#define	USB10_CMD_ENDP_S	20	
#define	USB10_CMD_ENDP_M	0x0f
#define	USB10_CMD_ENDP(X)	(((X) >> USB10_CMD_ENDP_S) & USB10_CMD_ENDP_M)
#define	USB10_CMD_SET_ENDP(X)	(((X) & USB10_CMD_ENDP_M) << USB10_CMD_ENDP_S)

#define	USB10_CMD_LEN_S		8
#define	USB10_CMD_LEN_M		0xfff
#define	USB10_CMD_LEN(X)	(((X) >> USB10_CMD_LEN_S) & USB10_CMD_LEN_M)
#define	USB10_CMD_SET_LEN(X)	(((X) & USB10_CMD_LEN_M) << USB10_CMD_LEN_S)

#define	USB10_CMD_PID_S		4
#define	USB10_CMD_PID_M		0x0f
#define	USB10_CMD_PID(X)	(((X) >> USB10_CMD_PID_S) & USB10_CMD_PID_M)
#define	USB10_CMD_SET_PID(X)	(((X) & USB10_CMD_PID_M) << USB10_CMD_PID_S)

#define	USB10_CMD_S		0
#define	USB10_CMD_M		0x0f
#define	USB10_CMD(X)		(((X) >> USB10_CMD_S) >> USB10_CMD_M)
#define	USB10_CMD_SET(X)	(((X) & USB10_CMD_M) << USB10_CMD_S)

#define	USB10_CMD_NONE		0x00
#define	USB10_CMD_SEND_TOKEN	0x01	// Send arbitrary token
#define	USB10_CMD_SEND_DATA	0x02	// Send data packet
#define	USB10_CMD_BUS_RESET	0x03	// Initiate Bus Reset state

#define	USB10_STATE_UNCONNECTED	0
#define	USB10_STATE_IDLE	1
#define	USB10_STATE_TOKEN_SEND	2

#define	USB10_CONTROL_ENABLE_S	31
#define	USB10_CONTROL_ENABLE_M	0x01
#define	USB10_CONTROL_ENABLE(X)	(((X) >> USB10_CONTROL_ENABLE_S) & USB10_CONTROL_ENABLE_M)
#define	USB10_CONTROL_ENABLE_BIT	(USB10_CONTROL_ENABLE_M << USB10_CONTROL_ENABLE_S)

#define	USB10_CONTROL_KEEPALIVE_S	30
#define	USB10_CONTROL_KEEPALIVE_M	0x01
#define	USB10_CONTROL_KEEPALIVE(X)	(((X) >> USB10_CONTROL_KEEPALIVE_S) & USB10_CONTROL_KEEPALIVE_M)
#define	USB10_CONTROL_KEEPALIVE_BIT	(USB10_CONTROL_KEEPALIVE_M << USB10_CONTROL_KEEPALIVE_S)

#define	USB10_CONTROL_RESET_DELAY_S		0	
#define	USB10_CONTROL_RESET_DELAY_M		0xffff
#define	USB10_CONTROL_RESET_DELAY(X)		(((X) >> USB10_CONTROL_RESET_DELAY_S) & USB10_CONTROL_RESET_DELAY_M)
#define	USB10_CONTROL_RESET_DELAY_SET(X)	(((X) & USB10_CONTROL_RESET_DELAY_M) << USB10_CONTROL_RESET_DELAY_S)


#define	USB10_PID_SETUP		0b1101	// "1011 0100"	SETUP 	Address for host-to-device control transfer
#define	USB10_PID_DATA0		0b0011	// "1100 0011"	DATA0 	Even-numbered data packet
#define	USB10_PID_DATA1		0b1011	// "1101 1101"	DATA1  	Odd-numbered data packet
#define	USB10_PID_IN		0b1001	// "1001 0110"	IN	Address for device-to-host transfer


#pragma pack(1)
typedef struct {
	volatile uint32_t STATUS;
	volatile uint32_t COMMAND;
	volatile uint32_t RECV_DATA_LOW;
	volatile uint32_t RECV_DATA_HIGH;
	volatile uint32_t SEND_DATA_LOW;
	volatile uint32_t SEND_DATA_HIGH;
	volatile uint32_t CRC16;
	volatile uint32_t CRC5;
	volatile uint32_t CONTROL;
} USB10_Reg;
#pragma pack(0)


int usb10_wait_cmd_complete(USB10_Reg* reg, int timeout); 


#endif /* __USB10_H__ */

